version: '3.4'

services:
 sqldata:
  environment:
   - SA_PASSWORD=P@ssw0rd
   - ACCEPT_EULA=Y
  ports:
  - "5433:1433"
  volumes:
  - eshop-sqldata:/var/opt/mssql

 catalog-api:
  #environment: 
  # - ASPNETCORE_ENVIRONMENT=Development
  # - PATH_BASE=${PATH_BASE}
  env_file:
   - catalog.env
  environment:
   - ASPNETCORE_ENVIRONMENT=Development
   - ConnectionString=${ESHOP_CATALOG_DB:-Server=sqldata;Database=Services.CatalogDb;User Id=sa;Password=P@ssw0rd}
   - PATH_BASE=${PATH_BASE}
   - SeqServerUrl=${SeqServerUrl}
   - LogstashServerUrl=${LogstashServerUrl}
  ports:
  - "5101:80"
  - "9101:81"

volumes:
  eshop-sqldata:
   external: false